In [ ]:
# 1-matris; numpyda satir ve sutunlardan olusan tek ya da cok boyutlu arraylere matris denir. Eger bir matris tek siradan olusuyorsa buna vektor adi verilir.

In [2]:
# 2-10 elemanli bir listeden NumPy Array’i olusturunuz.
import numpy as np 
list_a=[1,2,3,4,5,6,7,8,9,0]
array_a=np.array(list_a)
array_a

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [3]:
# 3-Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.
a =np.zeros((10,10),dtype="int32")
a


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [4]:
# 4-Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.
b=np.ones((10,10),dtype="float")
b

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
# 5-Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.
c=np.full((10,10),9,dtype="int32")
c

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]], dtype=int32)

In [7]:
# 6-5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.
d=np.arange(5,25,3)
d

array([ 5,  8, 11, 14, 17, 20, 23])

In [8]:
# 7--1 ile 1 arasinda 30 adet Array olusturunuz.
e=np.linspace(-1,1,30)
e

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

In [9]:
# 8-0 ile 30 arasinda 5x6’lik bir matris olusturun.
f=np.random.randint(0,30,(5,6))
f

array([[25,  8, 10,  0, 18,  8],
       [18, 25, 11, 29, 27,  7],
       [29,  9, 13, 16,  2, 27],
       [28, 24,  9, 19, 12, 11],
       [21, 20, 17, 28, 15, 26]])

In [10]:
# 9-Kosegenleri 1 olan 10x10’luk bir matris olusturunuz.
g=np.eye(10)
g

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [1]:
# 10- 0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin;
# 	•	eleman sayisini
# 	•	boyut bilgisini/sayisini
# 	•	satir X sutun bilgisini
# 	•	veri tipini numpy metodlariyla yazdiriniz.
import numpy as np
h=np.random.randint(0,10,(5,10))
h_eleman=h.size
h_boyut=h.ndim
h_ssbilgi=h.shape
h_veritipi=h.dtype
h_eleman,h_boyut,h_ssbilgi,h_veritipi

(50, 2, (5, 10), dtype('int64'))

In [13]:
# 11- 0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak)
i= np.random.randint(0,10, size=(3,4,7))
i

array([[[1, 9, 1, 9, 6, 7, 2],
        [4, 1, 0, 3, 6, 5, 2],
        [5, 0, 1, 0, 7, 0, 0],
        [4, 1, 9, 7, 2, 3, 2]],

       [[6, 5, 4, 2, 8, 0, 9],
        [3, 7, 0, 8, 8, 1, 6],
        [2, 6, 8, 5, 0, 5, 0],
        [8, 3, 5, 8, 0, 7, 9]],

       [[3, 6, 0, 4, 4, 8, 6],
        [6, 5, 7, 9, 2, 7, 1],
        [7, 4, 5, 4, 9, 2, 1],
        [5, 9, 8, 2, 7, 9, 8]]])

In [14]:
# 12-Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)
vektor = np.arange(1,13)
matris = vektor.reshape(3,4)
matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [1]:
# 13- 4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.
import numpy as np
x=np.array([1,2,3])
y=np.array([4,5,6])
w=np.array([7,8,9])
z=np.array([0,-1,-2])

q=np.concatenate([x,y,w,z])
q

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  0, -1, -2])

In [11]:
# 14-2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz,
v = np.random.randint(0,10, size=(2,1,4))
m = np.random.randint(0,10, size=(2,2,4))
vm = np.concatenate([v,m], axis=1)
vm

array([[[2, 6, 2, 3],
        [9, 7, 8, 3],
        [3, 5, 6, 5]],

       [[4, 6, 6, 3],
        [5, 0, 6, 0],
        [0, 3, 5, 4]]])

In [ ]:
# 15- Numpy da arraylari birlestirme islemleri concatenate() metodu ile yapilir. default axis=0 dir. Bu satir bazli birlestirme yapar. Yani alt alta dogru arrayleri birlestirilir. axis=1 ise sutun bazli birlestirme yapmak icin 2.arguman olarak kullanilir. Yani yana dogru arrayler birlestirilir.

In [15]:
# 16- Farkli boyutlardaki arraylari satir ve sutun bazli ayri ayri birlestiriniz.
a=np.array([1,2,3])
b=np.array([[4,5,6],
            [9,9,0]])
ab=np.vstack([b,a]) 

k=np.array([[1],
            [3]])
l=np.array([[4,5,6],
            [9,9,0]])
kl=np.hstack([k,l]) 
ab, kl  

(array([[4, 5, 6],
        [9, 9, 0],
        [1, 2, 3]]),
 array([[1, 4, 5, 6],
        [3, 9, 9, 0]]))

In [17]:
# 17- 10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 4 ayri array olusturunuz.
liste=[1,2,3,4,5,6,7,8,9,0]
s=np.split(liste,[2,6,8]) # 3 yerden ayirldigim icin 4 farkli np array olusturdu
a,b,c,d=s
a, b, c, d

(array([1, 2]), array([3, 4, 5, 6]), array([7, 8]), array([9, 0]))

In [7]:
# 18- Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.Ve bu siralamadan sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.
import numpy as np
s=np.random.randint(0,10,8)
n=np.sort(s)
n[6]

8

In [10]:
# 19- 20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.
v=np.random.randint(0,10,20)
v[2],v[4],v[6]

(9, 7, 7)

In [11]:
# 20- 10 elemanli random bir vektor olusturunuz ve bu arrayin  4. elemanini farkli bir sayiyla degistiriniz.
a=np.random.randint(0,100,10)
a[5]=99

In [ ]:
# 21-Bir kare matriste asal köşegen üzerindeki elemanların dışında kalan tüm elemanlar sıfır ise bu matrise “Diagonal Matrix” denir. “Trace Matrix” ise bu elemanlarin toplamina denir

In [36]:
# 22- 5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)
d=np.eye(5)
np.where(d==1),d[0,0],d[1,1],d[2,2],d[3,3],d[4,4]

((array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4])), 1.0, 1.0, 1.0, 1.0, 1.0)

In [14]:
# 23-10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.
v=np.arange(10,20)
v[2:]

array([12, 13, 14, 15, 16, 17, 18, 19])

In [2]:
# 24 - 10X10 luk bir matris olusturunuz ve ;
# 3.satir ve 5.sutuna ulasiniz.
import numpy as np
m=np.random.randint(0,20,(10,10))
m[2,4]

12

In [5]:
#25- 5.sutunun tum satirlarina ulasiniz. araay=[bas:son satirlar , bas:son sutunlar]
	
m[:,4]    

array([19, 11, 12,  9, 16, 16, 18,  6, 18,  7])

In [6]:
# 26- Tum sutunlarin 2.satirlarina ulasiniz.
m[1, : ]

array([ 0, 13, 14,  3, 11, 16,  2,  5,  0, 18])

In [22]:
# 27- tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.
m[ 2:7 , : ]

array([[   5,   14,   17,   18,   12,   13,    8,    9,   13,    5],
       [  12,    1,   16,    6,    9,   13,    9,    8,    6,    9],
       [   7,   14,    5,   14, 1986,   18,    0,    6,   12,   17],
       [  13,   10,    5,   19,   16, 1986,    1,    6,    8,    4],
       [  12,   14,   15,   14,   18,   15,    4,   13,    4,    2]])

In [21]:
# 28- satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.
m[2:5,3:7]

array([[  18,   12,   13,    8],
       [   6,    9,   13,    9],
       [  14, 1986,   18,    0]])

In [11]:
# 29- satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.
m[5: , :4]

array([[13, 10,  5, 19],
       [12, 14, 15, 14],
       [18,  9,  5,  4],
       [17, 13, 15,  0],
       [19,  2,  2,  8]])

In [14]:
# 30- sutun indexi sadece 3, 6,9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.
m[:,:3]

array([[19,  6,  4],
       [ 0, 13, 14],
       [ 5, 14, 17],
       [12,  1, 16],
       [ 7, 14,  5],
       [13, 10,  5],
       [12, 14, 15],
       [18,  9,  5],
       [17, 13, 15],
       [19,  2,  2]])

In [20]:
# 31- 5. indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz. 
m[5,5]=1986


array([[  19,    6,    4,   16,   19,   18,    3,    5,   17,    1],
       [   0,   13,   14,    3,   11,   16,    2,    5,    0,   18],
       [   5,   14,   17,   18,   12,   13,    8,    9,   13,    5],
       [  12,    1,   16,    6,    9,   13,    9,    8,    6,    9],
       [   7,   14,    5,   14, 1986,   18,    0,    6,   12,   17],
       [  13,   10,    5,   19,   16, 1986,    1,    6,    8,    4],
       [  12,   14,   15,   14,   18,   15,    4,   13,    4,    2],
       [  18,    9,    5,    4,    6,   13,   19,    7,    7,    7],
       [  17,   13,   15,    0,   18,   14,    1,   13,    7,   19],
       [  19,    2,    2,    8,    7,   10,    1,    1,    9,    0]])

In [28]:
# 32 -0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin;   20 den buyuk olan kac deger var.
a=np.arange(0,50,5)
np.greater(a,20)

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [29]:
# 33- 	30’dan kucuk kac deger var
np.less(a,30)

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False])

In [30]:
# 34- 	icerisinde 33 gecen kac deger var
np.equal(a,33)

array([False, False, False, False, False, False, False, False, False,
       False])

In [31]:
# 35- 	olusturulan arrayin tum elemanlarini 5 ile carpin.
np.multiply(a,5)

array([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225])

In [32]:
# 36- olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.
a%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [38]:
# 37- 0 ile 1 arasinda 50 elamanli bir array olusturunuz ve;	orlamasini aliniz.
j=np.arange(0,50)
np.mean(j)

24.5

In [37]:
# 38- standart sapmasini aliniz.
np.std(j)

14.430869689661812

In [39]:
#39- 	varyansini aliniz.
np.var(j)

208.25

In [36]:
#40-	median’ini aliniz.
np.median(j)    

24.5

In [34]:
#41-	en kucuk degeri bulunuz.
np.min(j)	

0

In [35]:
# 42-	en buyuk degeri bulunuz.
np.max(j)

49